### ISSUE TITLE
Add Aloe Model to MedConceptsQA Leaderboard

### ISSUE THREAD

**Issue by OscarMoliina** [nadavlab/MedConceptsQA#3]
Hello! We'd like to request the addition of our model, **Aloe**, to the MedConceptsQA leaderboard. Here are the HuggingFace model names:

- `HPAI-BSC/Llama3.1-Aloe-Beta-8B`
- `HPAI-BSC/Llama3.1-Aloe-Beta-70B`

Thank you for considering this submission! Please let us know if there’s any further information needed.

**Comment by Ofir408** [comment]
Hi @OscarMoliina
Thank you for reaching out!
I've added your models to our leaderboard.


Zero Shot:
![image](https://github.com/user-attachments/assets/df8dabac-5286-4dcd-8327-08399bea7461)

Few Shot:
![image](https://github.com/user-attachments/assets/978b7e8f-8a5b-4df3-aada-cd3e4b039e41)

You are welcome to include these results in your official paper when reporting on the MedConceptsQA benchmark.
